name = "AURORA"
uuid = "4b0706e8-6e74-4116-ab4c-be5c58cc7d1d"
version = "0.6.0"
authors = ["Etienne <etienne.gavazzi@uit.no>"]

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
AURORA_viz = "Makie"

[compat]
julia = "1.10"
CondaPkg = "0.2"
DataInterpolations = "8.8"
DelimitedFiles = "1.9"
HCubature = "1.8"
Integrals = "4.8, 5.1"
Interpolations = "0.16"
JSON = "1.3"
KLU = "0.6"
LoopVectorization = "0.12.173"
MAT = "0.11"
PrecompileTools = "1.2.1"
ProgressMeter = "1.11"
PythonCall = "0.9"
QuadGK = "2.11"
Rotations = "1.7"
SpecialFunctions = "2.6"
Term = "2.0"
TestItemRunner = "1.1"
TestItems = "1.0"
Dates = "1.10"
Distributed = "1.10"
Downloads = "1.6"
LibGit2 = "1.10"
LinearAlgebra = "1.10"
Pkg = "1.10"
Printf = "1.10"
SparseArrays = "1.10"
Statistics = "1.10"
Test = "1.10"
Makie = "0.22 - 0.24"
